name: Build NextJS App
description: Installs dependencies and builds Next.js
runs:
  using: composite
  steps:
    - name: Install Node Dependencies
      uses: pnpm/action-setup@v4
      with:
        version: 9.2.0

    - name: Determine architecture
      id: arch
      shell: bash
      run: |
        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then
          echo "arch=amd64" >> $GITHUB_OUTPUT
        elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
          echo "arch=arm64" >> $GITHUB_OUTPUT
        else
          echo "arch=$ARCH" >> $GITHUB_OUTPUT
        fi

    - name: Cache pnpm packages
      uses: actions/cache@v4
      with:
        path: |
          ./node_modules
          ~/.npm
          ~/.config
          ~/.pnpm-store
        key: ${{ runner.os }}-${{ steps.arch.outputs.arch }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      shell: bash
      run: pnpm i

    - name: Build NextJS App
      shell: bash
      run: npm run envs:reset

    - name: Build NextJS App
      working-directory: ./apps/web
      shell: bash
      run: pnpm run build
