name: open-cuak-apps
services:
  open-cuak-web:
    build:
      context: ../
      dockerfile: apps/web/Dockerfile
      args:
        TARGETARCH: ${TARGETARCH}
      cache_from:
        - open-cuak-web:latest
    platform: 'linux/${TARGETARCH}'
    image: open-cuak-web
    container_name: open-cuak-web
    restart: always
    ports:
      - '3000:3000'
    networks:
      - default
      - supabase_supabase-network
    volumes:
      - ../.env.local:/app/apps/web/.env
      - ../.env.production:/app/apps/web/.env.production

  open-cuak-browserless:
    build:
      context: ../apps/browserless
      dockerfile: Dockerfile.production
      args:
        TARGETARCH: ${TARGETARCH}
    platform: 'linux/${TARGETARCH}'
    image: open-cuak-browserless
    container_name: open-cuak-browserless
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '11975:11975'
      - '11976:3000'
      - '50000:50000'
    networks:
      - default
      - supabase_supabase-network
    volumes:
      - ../.env.local:/app/.env
      - ../.env.production:/app/.env.production

networks:
  supabase_supabase-network:
    external: true
