name: CI Web App

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  DOCK_IMAGE_NAME: aident-ai/open-cuak-web

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Prettier
        id: prettier-run
        uses: rutajdash/prettier-cli-action@v1.0.0
        with:
          config_path: ./.prettierrc
      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{steps.prettier-run.outputs.prettier_output}}"

  next-build:
    name: Build Web App
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Build NextJS App
        uses: ./.github/actions/build-web-app

  docker-build:
    name: Deploy Web App
    runs-on: ubuntu-latest
    needs: next-build
    if: github.event_name == 'push'
    steps:
      - name: Build NextJS App
        uses: ./.github/actions/build-web-app

      # Build and push Docker image
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        working-directory: ./apps/web
        run: docker build -f Dockerfile -t ${{ env.DOCK_IMAGE_NAME }}:${{ steps.commit.outputs.short }} ../../
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag Docker image for GHCR
        run: |
          docker tag ${{ env.DOCK_IMAGE_NAME }}:${{ steps.commit.outputs.short }} ghcr.io/${{ env.DOCK_IMAGE_NAME }}:${{ steps.commit.outputs.short }}
          docker tag ${{ env.DOCK_IMAGE_NAME }}:${{ steps.commit.outputs.short }} ghcr.io/${{ env.DOCK_IMAGE_NAME }}:latest
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.DOCK_IMAGE_NAME }}:${{ steps.commit.outputs.short }}
          docker push ghcr.io/${{ env.DOCK_IMAGE_NAME }}:latest
